apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
  spec:
    containers:
    - name: hello-world
      image: kmbeducative/python-sample:3.0
      imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

